- name: Listen for RHEL Performance Co-Pilot events
  hosts: all
  sources:
    - ansible.eda.webhook:
        host: 0.0.0.0
        port: 5000
  rules:
    - name: Test
      condition: event.payload.pcp.pmie.rule == "Test actions"
      action:
        run_job_template:
          name: eda-test
          organization: Default
          job_args:
            extra_vars:
               message: {{ event.payload.pcp.pmie.values }}
               sleep: 1
               
