- name: Listen for RHEL Performance Co-Pilot events
  hosts: all
  sources:
    - ansible.eda.webhook:
        host: 0.0.0.0
        port: 5000
  rules:
    - name: Respond to PMIE rule for High average processor utilization
      condition: event.payload.pcp.pmie.rule == "High average processor utilization"      
      action:
        run_job_template:
          name: eda-test
          organization: Default
#          job_args:
#            extra_vars:
#               message: from eda
               #payload: "{{ event.payload.pcp.pmie.values }}"
#               sleep: 1
               
    - name:  test
      condition: event.payload is defined
      action:
        debug:
          #msg: "Received: {{ event.payload }} from host {{ event.payload | regex_search('@(\\S+)', '\\1') | first }}"
          msg: "Received: {{ event.payload.pcp.pmie.values }}"
