- name: Listen for RHEL Performance Co-Pilot events
  hosts: all
  sources:
    - ansible.eda.webhook:
        host: 0.0.0.0
        port: 5000
  rules:
    - name: Test
      condition: event.payload.pcp.pmie.rule == "Test actions"
      action:
        run_job_template:
          name: eda-test
          organization: Default
          job_args:
            extra_vars:
               message: from eda
               host: "{{ event.payload | regex_search('@(\\S+)', '\\1') | first }}"
               sleep: 1
               
    - name:  test
      condition: event.payload is defined
      action:
        debug:
          msg: "Received: {{ event.payload }} from host {{ event.payload | regex_search('@(\\S+)', '\\1') | first }}"
